#pragma once

#ifdef _WIN32

#include <winsock2.h>
#include <ws2tcpip.h>

#define NET_EINTR           WSAEINTR
#define NET_EACCES          WSAEACCES
#define NET_EFAULT          WSAEFAULT
#define NET_EINVAL          WSAEINVAL
#define NET_EMFILE          WSAEMFILE
#define NET_EAGAIN          WSAEWOULDBLOCK
#define NET_EWOULDBLOCK     WSAEWOULDBLOCK
#define NET_EINPROGRESS     WSAEINPROGRESS
#define NET_EALREADY        WSAEALREADY
#define NET_ENOTSOCK        WSAENOTSOCK
#define NET_EDESTADDRREQ    WSAEDESTADDRREQ
#define NET_EMSGSIZE        WSAEMSGSIZE
#define NET_EPROTOTYPE      WSAEPROTOTYPE
#define NET_ENOPROTOOPT     WSAENOPROTOOPT
#define NET_EPROTONOSUPPORT WSAEPROTONOSUPPORT
#define NET_ESOCKTNOSUPPORT WSAESOCKTNOSUPPORT
#define NET_ENOTSUP         WSAEOPNOTSUPP
#define NET_EPFNOSUPPORT    WSAEPFNOSUPPORT
#define NET_EAFNOSUPPORT    WSAEAFNOSUPPORT
#define NET_EADDRINUSE      WSAEADDRINUSE
#define NET_EADDRNOTAVAIL   WSAEADDRNOTAVAIL
#define NET_ENETDOWN        WSAENETDOWN
#define NET_ENETUNREACH     WSAENETUNREACH
#define NET_ENETRESET       WSAENETRESET
#define NET_ECONNABORTED    WSAECONNABORTED
#define NET_ECONNRESET      WSAECONNRESET
#define NET_ENOBUFS         WSAENOBUFS
#define NET_EISCONN         WSAEISCONN
#define NET_ENOTCONN        WSAENOTCONN
#define NET_ESHUTDOWN       WSAESHUTDOWN
#define NET_ETIMEDOUT       WSAETIMEDOUT
#define NET_ECONNREFUSED    WSAECONNREFUSED
#define NET_EHOSTDOWN       WSAEHOSTDOWN
#define NET_EHOSTUNREACH    WSAEHOSTUNREACH
#define NET_ESYSNOTREADY    WSASYSNOTREADY
#define NET_NOTINITIALISED        WSANOTINITIALISED
#define NET_HOST_NOT_FOUND  WSAHOST_NOT_FOUND
#define NET_TRY_AGAIN       WSATRY_AGAIN
#define NET_NO_RECOVERY     WSANO_RECOVERY
#define NET_NO_DATA         WSANO_DATA

#else

#include <unistd.h>
#include <arpa/inet.h>

#define NET_EINTR           EINTR
#define NET_EACCES          EACCES
#define NET_EFAULT          EFAULT
#define NET_EINVAL          EINVAL
#define NET_EMFILE          EMFILE
#define NET_EAGAIN          EAGAIN
#define NET_EWOULDBLOCK     EWOULDBLOCK
#define NET_EINPROGRESS     EINPROGRESS
#define NET_EALREADY        EALREADY
#define NET_ENOTSOCK        ENOTSOCK
#define NET_EDESTADDRREQ    EDESTADDRREQ
#define NET_EMSGSIZE        EMSGSIZE
#define NET_EPROTOTYPE      EPROTOTYPE
#define NET_ENOPROTOOPT     ENOPROTOOPT
#define NET_EPROTONOSUPPORT EPROTONOSUPPORT
#define NET_ESOCKTNOSUPPORT ESOCKTNOSUPPORT
#define NET_ENOTSUP         ENOTSUP
#define NET_EPFNOSUPPORT    EPFNOSUPPORT
#define NET_EAFNOSUPPORT    EAFNOSUPPORT
#define NET_EADDRINUSE      EADDRINUSE
#define NET_EADDRNOTAVAIL   EADDRNOTAVAIL
#define NET_ENETDOWN        ENETDOWN
#define NET_ENETUNREACH     ENETUNREACH
#define NET_ENETRESET       ENETRESET
#define NET_ECONNABORTED    ECONNABORTED
#define NET_ECONNRESET      ECONNRESET
#define NET_ENOBUFS         ENOBUFS
#define NET_EISCONN         EISCONN
#define NET_ENOTCONN        ENOTCONN
#define NET_ESHUTDOWN       ESHUTDOWN
#define NET_ETIMEDOUT       ETIMEDOUT
#define NET_ECONNREFUSED    ECONNREFUSED
#define NET_EHOSTDOWN       EHOSTDOWN
#define NET_EHOSTUNREACH    EHOSTUNREACH
#define NET_ESYSNOTREADY    -4
#define NET_NOTINITIALISED  -5
#define NET_HOST_NOT_FOUND  HOST_NOT_FOUND
#define NET_TRY_AGAIN       TRY_AGAIN
#define NET_NO_RECOVERY     NO_RECOVERY
#define NET_NO_DATA         NO_DATA

#endif
